In [1]:
import pandas as pd

df_train = pd.read_csv('fTrain.csv')
df_train.head()

,DateOfDeparture,Departure,CityDeparture,LongitudeDeparture,LatitudeDeparture,Arrival,CityArrival,LongitudeArrival,LatitudeArrival,WeeksToDeparture,...,CV,CV of norm,Distance,Norm Distance,Airports,Day,Month,Year,IsHolidays,PAX
0,2011-12-05,ORD,Chicago,0.747393,0.671019,EWR,Newark,0.688004,0.938417,8.352941,...,0.678473,0.137959,1527.939887,0.246995,2,5,12,2011,0,7
1,2013-03-01,ATL,Atlanta,0.362189,0.738700,LGA,New York,0.691918,0.944181,10.421053,...,0.959764,0.418331,1181.336943,0.184571,1,1,3,2013,0,7
2,2012-02-06,ORD,Chicago,0.747393,0.671019,BOS,Boston,0.765205,1.000000,9.250000,...,0.771548,0.230730,1879.752387,0.310356,2,6,2,2012,0,7
3,2012-12-10,ORD,Chicago,0.747393,0.671019,SFO,San Francisco,0.546078,0.000000,8.666667,...,0.854341,0.313252,3833.459735,0.662220,2,10,12,2012,0,7
4,2012-04-13,SFO,San Francisco,0.546078,0.000000,JFK,New York,0.685569,0.946004,14.037037,...,0.702324,0.161732,5403.554833,0.944995,2,13,4,2012,0,7

In [2]:
df_test = pd.read_csv('fTest.csv')
df_test.head()

,DateOfDeparture,Departure,CityDeparture,LongitudeDeparture,LatitudeDeparture,Arrival,CityArrival,LongitudeArrival,LatitudeArrival,WeeksToDeparture,...,Norm std,CV,CV of norm,Distance,Norm Distance,Airports,Day,Month,Year,IsHolidays
0,2012-10-21,DFW,Dallas-Fort Worth,0.328023,0.493226,SFO,San Francisco,0.546078,0.000000,14.600000,...,0.632963,0.792866,0.178700,2821.532925,0.479971,2,21,10,2012,0
1,2012-09-13,LAX,Los Angeles,0.376310,0.077221,ATL,Atlanta,0.362189,0.738700,14.730769,...,0.753192,0.907237,0.268260,3779.583120,0.652517,2,13,9,2012,0
2,2012-09-04,ORD,Chicago,0.747393,0.671019,IAH,Houston,0.193537,0.526253,8.470588,...,0.250433,0.694822,0.101925,823.505267,0.120126,2,4,9,2012,1
3,2012-08-13,DEN,Denver,0.649638,0.344594,PHX,Phoenix,0.352841,0.201740,8.200000,...,0.277814,0.767421,0.158775,845.501646,0.124087,2,13,8,2012,0
4,2012-09-10,ORD,Chicago,0.747393,0.671019,SEA,Seattle,1.000000,0.001277,12.090909,...,0.469124,0.755829,0.149698,3825.798893,0.660840,2,10,9,2012,0

In [3]:
y_train = df_train[['PAX']]

from sklearn.model_selection import train_test_split
df_train, df_test, y_train, y_test = train_test_split(df_train, y_train, test_size=0.2,random_state=42)#random_state=42

df_train.drop(df_train.columns[[0,2,3,4,6,7,8,9,10,12,13,14,15,22]], axis=1, inplace=True)
df_train.head()

,Departure,Arrival,Norm mean,Norm Distance,Airports,Day,Month,Year,IsHolidays
2755,IAH,ORD,0.274393,0.120126,2,9,11,2011,0
1941,DFW,LAS,0.266868,0.334983,2,2,11,2012,0
3424,LAX,JFK,0.845280,0.864365,2,3,8,2012,1
4081,LAX,SEA,0.476910,0.128889,2,21,9,2012,0
5505,DFW,DEN,0.333046,0.126730,2,12,9,2011,0

In [4]:
df_test.drop(df_test.columns[[0,2,3,4,6,7,8,9,10,12,13,14,15,22]], axis=1, inplace=True)
df_test.head()

,Departure,Arrival,Norm mean,Norm Distance,Airports,Day,Month,Year,IsHolidays
8833,LAX,DEN,0.465812,0.250046,2,10,4,2012,0
2025,LAX,SEA,0.429247,0.128889,2,27,2,2012,0
8209,DFW,PHL,0.281830,0.407744,2,25,3,2012,0
7870,DFW,SFO,0.498489,0.479971,2,8,11,2011,0
8085,ATL,ORD,0.322400,0.042168,2,10,9,2012,0

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df_train['Departure'])
df_train['Departure'] = le.transform(df_train['Departure'])
df_train['Arrival'] = le.transform(df_train['Arrival'])
df_test['Departure'] = le.transform(df_test['Departure'])
df_test['Arrival'] = le.transform(df_test['Arrival'])
#le.fit(df_train['CityDeparture'])
#df_train['CityDeparture'] = le.transform(df_train['CityDeparture'])
#df_train['CityArrival'] = le.transform(df_train['CityArrival'])
#df_test['CityDeparture'] = le.transform(df_test['CityDeparture'])
#df_test['CityArrival'] = le.transform(df_test['CityArrival'])
#le = LabelEncoder()
#le.fit(df_train['DateOfDeparture'])
#df_train['DateOfDeparture'] = le.transform(df_train['DateOfDeparture'])
#df_test['DateOfDeparture'] = le.transform(df_test['DateOfDeparture'])

In [6]:
from sklearn.preprocessing import OneHotEncoder
cf = [0,1,4,5,6,7,8]
enc = OneHotEncoder(categorical_features=cf,sparse=False)
enc.fit(df_train)
#enc.fit(df_test)
X_train = enc.transform(df_train)
X_test = enc.transform(df_test)
X_train.shape

C:\Users\IAKOVOS\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\IAKOVOS\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

(7119, 93)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
clf = RandomForestClassifier(random_state = 84)
def evaluate_param(parameter, num_range, index):
    grid_search = GridSearchCV(clf, param_grid = {parameter: num_range})
    grid_search.fit(X_train, y_train)
    
    df = {}
    for i, score in enumerate(grid_search.grid_scores_):
        df[score[0][parameter]] = score[1]
       
    
    df = pd.DataFrame.from_dict(df, orient='index')
    df.reset_index(level=0, inplace=True)
    df = df.sort_values(by='index')
 
    plt.subplot(3,2,index)
    plot = plt.plot(df['index'], df[0])
    plt.title(parameter)
    return plot, df

In [18]:
# parameters and ranges to plot
param_grid = {"n_estimators": np.arange(2, 300, 2),
              "max_depth": np.arange(1, 28, 1),
              "min_samples_split": np.arange(1,150,1),
              "min_samples_leaf": np.arange(1,60,1),
              "max_leaf_nodes": np.arange(2,60,1),
              "min_weight_fraction_leaf": np.arange(0.1,0.4, 0.1)}

In [ ]:
import matplotlib.pyplot as plt
index = 1
y_train = np.ravel(y_train)
plt.figure(figsize=(16,12))
for parameter, param_range in dict.items(param_grid):   
    evaluate_param(parameter, param_range, index)
    index += 1

In [7]:
#Random hyperparameter Grid
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
import numpy as np
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

print(random_grid)
y_train = np.ravel(y_train)
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)

# Fit the random search model
rf_random.fit(X_train, y_train)
print(rf_random.best_params_)

C:\Users\IAKOVOS\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}
Fitting 3 folds for each of 100 candidates, totalling 300 fits

[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed: 22.1min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed: 41.8min finished

{'n_estimators': 1600, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None, 'bootstrap': True}

In [7]:
#GRID SEARCH WITH CROSS_VALIDATION
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
y_train = np.ravel(y_train)
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [60],
    'max_features': ['auto'],
    'min_samples_leaf': [2],
    'min_samples_split': [5,10,15,20],
    'n_estimators': [1000,2000,3000,4000,5000],
    'class_weight': [None],
    'max_leaf_nodes':[None]
    }

# Create a based model
rf = RandomForestClassifier(random_state=42)

# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 3)



# Fit the grid search to the data
grid_search.fit(X_train, y_train)

grid_search.best_params_

C:\Users\IAKOVOS\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

Fitting 3 folds for each of 20 candidates, totalling 60 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:  8.5min finished

{'bootstrap': True,
 'class_weight': None,
 'max_depth': 60,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_samples_leaf': 2,
 'min_samples_split': 20,
 'n_estimators': 5000}

In [6]:
# Import the model we are using
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
#feature_list=list(df_train.columns)
y_train = np.ravel(y_train)
#X_train=df_train
#X_test=df_test
#est =[186,368,488,559,613,795,838,965];
#par={'n_estimators':est,
#     'random_state':[42]}
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(n_estimators=838,random_state=42)
rf.fit(X_train, y_train)
'''
# Get numerical feature importances
importances = list(rf.feature_importances_)

# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]

# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)

# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances]
# Train the model on training data
#clf= GridSearchCV(rf,par)
#clf.fit(X_train, y_train)
#print(clf.best_params_)
'''
y_pred = rf.predict(X_test)

Variable: DateOfDeparture      Importance: 0.1
Variable: WeeksToDeparture     Importance: 0.08
Variable: std_wtd              Importance: 0.08
Variable: Norm mean            Importance: 0.08
Variable: Norm std             Importance: 0.08
Variable: CV                   Importance: 0.08
Variable: CV of norm           Importance: 0.08
Variable: Day                  Importance: 0.08
Variable: Month                Importance: 0.06
Variable: Distance             Importance: 0.05
Variable: Norm Distance        Importance: 0.05
Variable: CityArrival          Importance: 0.04
Variable: Departure            Importance: 0.03
Variable: CityDeparture        Importance: 0.03
Variable: Arrival              Importance: 0.03
Variable: Year                 Importance: 0.02
Variable: IsHolidays           Importance: 0.02
Variable: Airports             Importance: 0.01

ValueError: Number of features of the model must match the input. Model n_features is 18 and input n_features is 22

In [8]:
import csv
from sklearn.metrics import f1_score
with open('y_predRF.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=',')
    writer.writerow(['Id', 'Label'])
    for i in range(y_pred.shape[0]):
        writer.writerow([i, y_pred[i]])
#f1_score(y_test, y_pred, average='micro')